server:
  port: 8180
spring:
  application:
    name: frame-config
  cloud:
    config:
      server:
        #default-application-name: frame-config
        git:
          uri: https://github.com/derrick-chen-git/config-file
          label: master
eureka:
  client:
    service-url:
      defaultZone:  http://47.106.212.169:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    #instance-id: ${spring.application.name}
    prefer-ip-address: true
